### ISSUE TITLE
utilize geolocation API

### ISSUE THREAD

**Issue by westwick** [infinite-robots/nomnom-ui#4]
instead of users having to type in their location or zip code, we should be able to auto detect it

**Comment by flurmbo** [comment]
This looks fun, can I work on this?

**Comment by westwick** [comment]
@flurmbo definitely!

**Comment by drewclem** [comment]
I'll look into this and see if it's something I can help with.

**Comment by maccyber** [comment]
Hah, I also gave it a go (in PR). It's so hard to find good hacktoberfest issues.
Maybe you guys can reuse some code and make it better.

**Comment by westwick** [comment]
closed by #6

**Comment by westwick** [comment]
should pop up the snackbar when it times out though, will open a new issue!
