### ISSUE TITLE
add touch gestures to restaurant cards

### ISSUE THREAD

**Issue by westwick** [infinite-robots/nomnom-ui#5]
Currently, users have to hit the 'yum' or 'nah' buttons to vote. Instead, we should enable touch support (hammerjs?) so users can swipe left/right on restaurants to vote (like tinder).

**Comment by ywpark1** [comment]
HI. I would like to work on this. Can I try this?

**Comment by westwick** [comment]
@ywpark1 yes please, let me know if you run into any issues!
